blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)
from django.views.generic import TemplateView


urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')), 
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^login/$', TemplateView.as_view(template_name="social_connect.html"), name='social-connect'),
    url(r'^about/$', TemplateView.as_view(template_name="portfolio.html"), name='portfolio'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	post_list_genre
	)


urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^genre/(?P<genre>[\w-]+)/$', post_list_genre, name='list-genre'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)
from django.views.generic import TemplateView
from Portfolio.views import portfolio


urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')), 
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^login/$', TemplateView.as_view(template_name="social_connect.html"), name='social-connect'),
    url(r'^about/$', portfolio , name='portfolio'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment

from .utils import get_read_time
# Create your models here.
# MVC MODEL VIEW CONTROLLER


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class Genre(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    image = models.CharField(max_length=1000)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft='NO').filter(publish__lte=timezone.now())

    def favourites(self, *args, **kwargs):
        return super(PostManager,self).filter(draft='NO').filter(publish__lte=timezone.now()).filter(favs=True)


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" %(new_id, filename)


draft_choice = (
    ('NO', 'NO'),
    ('YES', 'YES'),
    )
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    genre = models.ForeignKey(Genre)
    slug = models.SlugField(unique=True)
    image = models.CharField(max_length=1000)
    content = models.TextField()
    draft = models.CharField( max_length=5,choices=draft_choice,default='NO',)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    favs = models.BooleanField(default=False, verbose_name='Favourite')
    objects = PostManager()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)


class NewWriting(models.Model):
    title = models.CharField(max_length=120, null=False, blank=False)
    genre = models.ForeignKey(Genre, null=False, blank=False)
    name = models.CharField(max_length=1000, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    content = models.TextField(null=False, blank=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    join = models.CharField( max_length=5,choices=draft_choice,default='NO',verbose_name='Want to Join the team?')


    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

src/Portfolio/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.core.mail import EmailMessage

# Create your models here.




class Contact(models.Model):
	name = models.CharField(blank=False, null=False, max_length=200)
	email = models.EmailField(blank=False, null=False, max_length=200)
	subject = models.CharField(blank=False, null=False, max_length=200)
	message = models.TextField(blank=False, null=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.subject

	def __str__(self):
		return self.subject


def contact_post_saved_receiver(sender, instance, created, *args, **kwargs):
    obj = instance
    try:
      email = 'simrankr012@gmail.com'
      subject = obj.subject
      print subject

      message = "Message:" + obj.message +' <br> .This mail is sent by ' + obj.name + "<br> " + obj.email
      message=EmailMessage(subject=obj.subject,body=message,to=['simrankr012@gmail.com','jayesh.bidani@gmail.com'])
      message.content_subtype='html'
      message.send()

      message=EmailMessage(subject="Greetings from Writingbykaur",body="Hello " + obj.name + ".<br/> Thanks for reaching out to us. We will revert shortly.<br/> Have a nice day! </br> Regards </br> Writingsbykaur" ,to=[obj.email])
      message.content_subtype='html'
      message.send()

    except:
    	print "Failed"

post_save.connect(contact_post_saved_receiver, sender=Contact)

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post,NewWriting

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=True))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            'genre',
            "content",
            "image",
            "draft",
            "publish",
        ]

class NewWritingForm(forms.ModelForm):
    class Meta:
        model = NewWriting
        fields = [

        'title',
        'genre',
        'content',
        'join',
        ]

src/Portfolio/forms.py
from django import forms

from .models import Contact

class ContactForm(forms.ModelForm):
	name = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'id':'name','placeholder':'Name', 'type':'text'}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control', 'id':'email','placeholder':'Email', 'type':'email'}))
	subject = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'id':'subject','placeholder':'Subject', 'type':'text'}))
	message = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'id':'messagee','placeholder':'Message', 'type':'text'}))

	class Meta:
		model = Contact
		fields = [ "name","email","subject","message" ]

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post,NewWriting

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=True))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            'genre',
            "content",
            "image",
            "publish",
        ]

class NewWritingForm(forms.ModelForm):
    class Meta:
        model = NewWriting
        fields = [

        'title',
        'genre',
        'content',
        'join',
        ]

posts/views.py
try:
    from urllib import quote_plus #python 2
except:
    pass

try:
    from urllib.parse import quote_plus #python 3
except: 
    pass

from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm,NewWritingForm
from .models import Post, Genre

from django.contrib.auth.decorators import login_required

import random



@login_required(login_url="/login/")
def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	

	if instance.publish > timezone.now().date() or instance.draft == 'YES':
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)

	genre  = Genre.objects.all()

	initial_data = {
			"content_type": instance.get_content_type,
			"object_id": instance.id
	}

	context = {
		"genre":genre,
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
	}
	return render(request, "post.html", context)

def post_list(request):
	today = timezone.now().date()
	queryset_list = Post.objects.active() #.order_by("-timestamp")
	
	favourites_list = Post.objects.favourites()
	if favourites_list.count()< 5:
		 favourites_queryset_list = favourites_list
	else:
		favourites_queryset_list = random.sample(favourites_list,5)

	genre  = Genre.objects.all()
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 3) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)

	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"genre":genre,
		"object_list": queryset, 
		"favourites" : favourites_queryset_list,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "index.html", context)


def post_list_genre(request, genre):
	today = timezone.now().date()
	genre = genre

	print(genre)

	try:
		genre_id = Genre.objects.filter(title=genre)[0].id
		queryset_list = Post.objects.active().filter(genre=genre_id)
		print queryset_list
		genre  = Genre.objects.all()

	except:
		pass

	# queryset_list = Post.objects.active()

	favourites_list = Post.objects.favourites()
	if favourites_list.count()< 5:
		 favourites_queryset_list = favourites_list
	else:
		favourites_queryset_list = random.sample(favourites_list,5)

	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.filter(genre=genre_id)
	
	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 3) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)


	context = {
		"genre":genre,
		"object_list": queryset,
		"favourites" : favourites_queryset_list, 
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "index.html", context)



def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"title": instance.title,
		"instance": instance,
		"form":form,
	}
	return render(request, "create.html", context)

@login_required(login_url="/login/")
def post_create(request):
	if request.user.is_staff or request.user.is_superuser:
		form = PostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user = request.user
			instance.save()
			# message success
			messages.success(request, "Successfully Created")
			return HttpResponseRedirect(instance.get_absolute_url())
		context = {
			"form": form,
		}
		return render(request, "create.html", context)

	else:
		form = NewWritingForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			instance = form.save(commit=False)
			
			instance.name = request.user.first_name
			instance.email = request.user.email
			instance.save()
			return HttpResponseRedirect('/')

		context = {
			"form": form,
		}
		return render(request, "create.html", context)

def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

src/Portfolio/views.py
from django.shortcuts import render, redirect
from forms import ContactForm

# Create your views here.


def portfolio(request):
	data = {
		'name':'',
		'message':'',
		'subject':'',
		'message':''
	}
	form = ContactForm(data)
	if request.method=='POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			return redirect("posts:list")
	
	return render(request,"portfolio.html",{"form":form})

templates/create.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load socialaccount %}


<!--DOCTYPE html -->
<html>
<head>
<title>Writings By Kaur</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
        <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
        <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
        <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->


    <!-- jQuery Plugin -->
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.min.js"></script><!-- Latest compiled and minified CSS -->



<style>

</style>

{{ form.media }}

</head>
<body>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '672411446300358',
      xfbml      : true,
      version    : 'v2.9'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<div id="wrapper">

                <!-- Header -->
                    <header id="header">
                        <h1><a href="/">Writings By Kaur</a></h1>
                        <nav class="links">
                            <ul>

                            {% if request.user.is_authenticated %}
                                <li>Welcome {{ request.user.first_name }} </li>
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                {% else %}

                                <li>Welcome Guest</li>
                            {% endif %}

                                
                                {% for i in genre %}
                                <li><a href="{% url 'posts:list-genre' i.title %}">{{ i }}</a></li>                             
                                
                                {% endfor %}

                                {% if request.user.is_staff %}

                                <li><a href="{% url 'posts:create' %}">Create New Post</a></li>
                                {% endif %}
                                                                
                            </ul>
                        </nav>
                        <nav class="main">
                            <ul>
                                <li class="search">
                                    <a class="fa-search" href="#search">Search</a>
                                    <form id="search" method="get" action="#">
                                        <input type="text" type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}' />
                                    </form>
                                </li>
                                <li class="menu">
                                    <a class="fa-bars" href="#menu">Menu</a>
                                </li>
                            </ul>
                        </nav>
                    </header>

                    <section id="menu">

                    {% if not request.user.is_authenticated %}
                        <section>
                            
                        <ul class="actions vertical">
                                    {% providers_media_js %}
                                    <a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-block btn-social btn-facebook" style="background-color:#3b5998;text-align:center"><li class="button big fit" style="
    background-color: #4c4cff;">Login In With Facebook</li>
                                    </a>
                                </ul>

                    
                            </section>
                        {% endif %}

                        <!-- Search -->
                            <section>
                                <form class="search" method="get" action="#">
                                    <input type="text" type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}' />
                                </form>
                            </section>

                        <!-- Links -->
                            
                            <section>
                                <ul class="links">
                                    <li>
                                        <a href="#">
                                            <h3>{{ request.user.first_name }}{{ request.user.last_name }}</h3>
                                            <p>Feugiat tempus veroeros dolor</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Dolor sit amet</h3>
                                            <p>Sed vitae justo condimentum</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Feugiat veroeros</h3>
                                            <p>Phasellus sed ultricies mi congue</p>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <h3>Etiam sed consequat</h3>
                                            <p>Porta lectus amet ultricies</p>
                                        </a>
                                    </li>
                                </ul>
                            </section>

                        <!-- Actions -->
                            

                    </section>


                </div>


<div id="main">


<article class="post">
<center><h1>ENTER THE DETAILS HERE</h1></center>
<hr style="display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 3px;">

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form.as_p }}


<br/>
<input type='submit' class='btn btn-default' value='Create Post' />
</form>


</article>

</div>


<script src="{% static 'assets/js/jquery.min.js' %}"></script>
            <script src="{% static 'assets/js/skel.min.js' %}"></script>
            <script src="{% static 'assets/js/util.js' %}"></script>
            <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
            <script src="{% static 'assets/js/main.js' %}"></script>



<!-- Latest compiled and minified JavaScript -->
<script   src="https://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".content-markdown").each(function(){
            var content = $(this).text()
            var markedContent = marked(content)
            $(this).html(markedContent)
    })
    $(".wmd-panel wmd-preview img").each(function(){
            $(this).addClass("img-responsive");
    })
    
    var contentInput = $("#id_content");
    function setContent(value){
        var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())
    contentInput.keyup(function(){
        var newContent = $(this).val()
        setContent(newContent)
    })
    var titleInput = $("#id_title");
    
    function setTitle(value) {
        $("#preview-title").text(value)
    }
    setTitle(titleInput.val())
    titleInput.keyup(function(){
        var newContent = $(this).val()
        setTitle(newContent)
    })
    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
    // preview-title
    // preview-content
})
</script>



</body>
</html>

templates/social_connect.html
{% load staticfiles %}
{% load socialaccount %}
<!DOCTYPE html>

<html>
<head>
	<title></title>

<style type="text/css">
	
	@import url(https://fonts.googleapis.com/css?family=Roboto:300);

.login-page {
  width: 360px;
  padding: 8% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 100px;
  padding: 45px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 15px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #3b5998;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #3b5998;
}
.form .message {
  margin: 15px 0 0;
  color: #b3b3b3;
  font-size: 12px;
}
.form .message a {
  color: #4CAF50;
  text-decoration: none;
}
.form .register-form {
  display: none;
}
.container {
  position: relative;
  z-index: 1;
  max-width: 300px;
  margin: 0 auto;
}
.container:before, .container:after {
  content: "";
  display: block;
  clear: both;
}
.container .info {
  margin: 50px auto;
  text-align: center;
}
.container .info h1 {
  margin: 0 0 15px;
  padding: 0;
  font-size: 36px;
  font-weight: 300;
  color: #1a1a1a;
}
.container .info span {
  color: #4d4d4d;
  font-size: 12px;
}
.container .info span a {
  color: #000000;
  text-decoration: none;
}
.container .info span .fa {
  color: #EF3B3A;
}
body {
  background: #3b5998; /* fallback for old browsers */
  background: -webkit-linear-gradient(right, #3b5998, #8DC26F);
  background: -moz-linear-gradient(right, #3b5998, #8DC26F);
  background: -o-linear-gradient(right, #3b5998, #8DC26F);
  background: linear-gradient(to left, #3b5998, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}

</style>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.3.min.js"></script>


</head>
<body>

<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '672411446300358',
      xfbml      : true,
      version    : 'v2.9'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>


<div class="login-page">
  <div class="form">
    {% providers_media_js %}
									 
      <a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-block btn-social btn-facebook" ><button>login With Facebook</button></a>
      <br/>

      <p><h3><b>OR</b></h3></p><br/>
       <a href="{% url 'posts:list' %}" class="btn btn-block btn-social btn-facebook" ><button >Go Back</button></a>
  </div>
</div>

<script type="text/javascript">
	$('.message a').click(function(){
   $('form').animate({height: "toggle", opacity: "toggle"}, "slow");
});
</script>
</body>
</html>